name: CI
on:
  push:
  pull_request:

jobs:
  matrix-gen:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_dirs.outputs.matrix}}
    steps:
      - uses: actions/checkout@v2
      - id: list_dirs
        run: |
          MATRIX=$(ls -d app/* | sed 's:/*$::' | jq -cnR '[inputs | select(length>0)]')
          echo $MATRIX
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  compile-check:
    name: ${{ matrix.example }}
    needs: matrix-gen
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        example: ${{fromJson(needs.matrix-gen.outputs.matrix)}}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -yqq install build-essential libssl-dev

      - name: Build ${{ matrix.example }}
        run: cd ${{ matrix.example}} && make